### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ruidlpm** [ekirving/qpbrute#18]
Hello,

I am trying to install qpbrute, but running into problems with pip. Please see below for error messages. Thanks.

Option 1:
conda env create --name qpbrute --file https://raw.githubusercontent.com/ekirving/qpbrute/master/environment.yaml

Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: \
/
/
done
Installing pip dependencies: - Ran pip subprocess with arguments:
['/Users/rui/miniconda/envs/qpbrute/bin/python', '-m', 'pip', 'install', '-U', '-r', '/var/folders/3m/z7f6gb211p9ccr49s_q6dxnr0000gn/T/condaenv.1vqqcxr5.requirements.txt']
Pip subprocess output:
Collecting git+git://github.com/ekirving/qpbrute.git (from -r /var/folders/3m/z7f6gb211p9ccr49s_q6dxnr0000gn/T/condaenv.1vqqcxr5.requirements.txt (line 1))
  Cloning git://github.com/ekirving/qpbrute.git to /private/var/folders/3m/z7f6gb211p9ccr49s_q6dxnr0000gn/T/pip-req-build-2ovjzlnd

Pip subprocess error:
ERROR: Command errored out with exit status 128: git clone -q git://github.com/ekirving/qpbrute.git /private/var/folders/3m/z7f6gb211p9ccr49s_q6dxnr0000gn/T/pip-req-build-2ovjzlnd Check the logs for full command output.

failed

CondaEnvException: Pip failed

Option 2:

 pip install https://github.com/ekirving/qpbrute.git
Collecting https://github.com/ekirving/qpbrute.git
  Downloading https://github.com/ekirving/qpbrute.git
     \ 195.1 kB 1.5 MB/s 0:00:00
  ERROR: Cannot unpack file /private/var/folders/3m/z7f6gb211p9ccr49s_q6dxnr0000gn/T/pip-unpack-5iebhh9l/qpbrute.git (downloaded from /private/var/folders/3m/z7f6gb211p9ccr49s_q6dxnr0000gn/T/pip-req-build-nbzoxojq, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /private/var/folders/3m/z7f6gb211p9ccr49s_q6dxnr0000gn/T/pip-req-build-nbzoxojq

**Comment by ekirving** [comment]
Hi Rui, 

Sorry to hear that you ran into issues installing `qpBrute`. The error you encountered was caused by recent changes `GitHub` have made to their security protocols, such that `pip install https://github.com` no longer works, and has to be replaced with `pip install git+https://github.com`. I've made this change in the `environment.yaml` file and updated the README. 

Let me know if you run into any other issues.

Cheers,
Evan
