### ISSUE TITLE
qpBrute cannot resolve the graph

### ISSUE THREAD

**Issue by g-fabbri** [ekirving/qpbrute#22]
Dear Ervin,

I'm analyzing a dataset made of wild boar and domestic pig. 6 populations in total and one warthog as outgroup. The log file ends saying:
ERROR: Cannot resolve the graph from any permutation of the given nodes.
FINISHED: Found 0 unique solution(s) from a total of 10 unique graphs!

I upload the full log file too.

What could be the reason for this?

Thank you,
Giulia

[slurm_18590671_qpbrute.txt](https://github.com/ekirving/qpbrute/files/15079820/slurm_18590671_qpbrute.txt)

**Comment by ekirving** [comment]
Hi Giulia,

Have a look at this issue for some suggested reasons: https://github.com/ekirving/qpbrute/issues/5#issuecomment-519559277

Best wishes,
Evan
