### ISSUE TITLE
ERROR: Cannot place node 'CRM' in the graph.

### ISSUE THREAD

**Issue by jodyhey** [ekirving/qpbrute#5]
I wondered what might cause this.   Regardless of which populations I include, I get   this error: ERROR: Cannot place node  POP in the graph.  (POP changes) 
Here is a full screen 
[mparam.txt](https://github.com/ekirving/qpbrute/files/3482296/mparam.txt)

output, for example (param file attached):
jodyhey:~/downloads/qpbrute$ python2 qpbrute.py --par mparam.txt --prefix Macaca_19Genomes_small --pops CRM  CEM TM  --out SYL
INFO: There are 6 possible starting orders for the given nodes.
INFO: Performing an exhaustive search.
INFO: Starting list ['CRM', 'CEM', 'TM']
(SYL,(CEM,CRM));                                                                        nodes=3  admix=0         outliers=6         worst=-22.760    8ea32e7
ERROR: Cannot place node 'CEM' in the graph.
INFO: Starting list ['TM', 'CEM', 'CRM']
(SYL,(CEM,TM));                                                                         nodes=3  admix=0         outliers=5         worst=-25.513    ed0d541
ERROR: Cannot place node 'CEM' in the graph.
INFO: Starting list ['CRM', 'CEM', 'TM']
(SYL,(CEM,CRM));                                                                        nodes=3  admix=0         outliers=6         worst=-22.760    8ea32e7
ERROR: Cannot place node 'CEM' in the graph.
INFO: Starting list ['TM', 'CRM', 'CEM']
(SYL,(CRM,TM));                                                                         nodes=3  admix=0         outliers=6         worst=-25.252    7a7ea17
ERROR: Cannot place node 'CRM' in the graph.
INFO: Starting list ['CEM', 'TM', 'CRM']
(SYL,(CEM,TM));                                                                         nodes=3  admix=0         outliers=5         worst=-25.513    ed0d541
ERROR: Cannot place node 'TM' in the graph.
INFO: Starting list ['CRM', 'TM', 'CEM']
(SYL,(CRM,TM));                                                                         nodes=3  admix=0         outliers=6         worst=-25.252    7a7ea17
ERROR: Cannot place node 'TM' in the graph.
INFO: Starting list ['CEM', 'CRM', 'TM']
(SYL,(CEM,CRM));                                                                        nodes=3  admix=0         outliers=6         worst=-22.760    8ea32e7
ERROR: Cannot place node 'CRM' in the graph.
ERROR: Cannot resolve the graph from any permutation of the given nodes.
FINISHED: Found 0 unique solution(s) from a total of 3 unique graphs!
INFO: Permute execution took: 0:04:46.730491

**Comment by ekirving** [comment]
Hi Jody,

Those errors indicate that of all possible 3-population trees, there are none which are an acceptable fit for the observed patterns of allele sharing in your populations.

My method assumes that there is at least one 3-population tree which fits the data, and from there it iteratively adds extra populations (including via admixture branches).

The most likely scenarios (without having any knowledge about your data) are:
* your outgroup is too closely related to your ingroup
* your outgroup has admixed with your ingroup
* your outgroup is inbred, in which case you need to set `outpop:  NULL` in your mparam.txt file (see https://github.com/DReichLab/AdmixTools/blob/master/README.QPGRAPH for more details)

Cheers,
Evan

**Comment by jodyhey** [comment]
outpop: NULL  did the trick 

thanks

is there a downside to using outpop: NULL  ?

**Comment by ekirving** [comment]
If your outgroup population is outbred and has multiple individuals, then you will get a more accurate result using `outpop:  POPNAME`, as the allele frequency of the outgroup is used to normalise the weighting of each SNP in the ingroup.

But if your outgroup population does not have a reliable allele frequency, then attempting to normalise with that frequency will cause all models to fail.

From the [qpGraph code](https://github.com/DReichLab/AdmixTools/blob/master/src/qpGraph.c#L419):
```
outpop:  NULL (snps are flat weighted)
outpop:  NONE  snps are weighted  1/ (p * (1--p))  where p is the allele frequency  in the entire sample
outpop:  Mbuti (say)   snps are weighted 1/ (p*(1-p)) where p is allele frequency in Mbuti
```
